# Generated by Django 4.2.24 on 2025-09-29 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fantasy_ttpremier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Team", max_length=100)),
                (
                    "players",
                    models.ManyToManyField(blank=True, to="fantasy_ttpremier.player"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
